server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: neo_route
        uri: lb://service-provider
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix= 1
        - name: Hystrix
          args:
            name: fetchIngredients
            fallbackUri: forward:/fallback
      - id: neo_route2
          uri: lb://service-provider2
          predicates:
          - Path=/demo2/**
          filters:
          - StripPrefix= 1
          - name: Hystrix
            args:
              name: fetchIngredients
              fallbackUri: forward:/fallback