server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: neo_route
        uri: lb://service-provider
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1
        - name: Token
        - name: Hystrix
          args:
            name: fetchIngredients
            fallbackUri: forward:/fallback
        - IPForbid=0:0:0:0:0:0:0:1
        - MyTest=lojzes,mans
